spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maverick
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true